Parameters:
  Region: "cn-hangzhou"
  Name: "bot-detect-plugin"
SceneMetadata:
  Name:
    zh-cn: "bot-detect 插件"
    en: "Bot Detect Plugin"
  Description:
    zh-cn: "bot-detect 插件可以用于识别并阻止互联网爬虫对站点资源的爬取"
    en: "The bot-detect plug-in can be used to identify and prevent Web crawlers from crawling site resources"
  Logo: "resources/icons/scence_logo.png"
SceneProfiles:
  - DisplayName:
      zh-cn: 单机版
      en: Single Service
    Template: "templates/msa.yml"
    Documentation:
      zh-cn: "docs/zh-cn/index.md"
    Parameters:
      Backend:
        Cpu: 1
        Memory: 4096
        Handler: index.handler
    TestCase:
      Method: "GET"
      Path: "/get"
      Header:
        User-Agent: spd-tools

