Parameters:
  Region: "cn-hangzhou"
  Name: "key-auth-plugin"
  GatewayId: gw-cvcpbhum1hkhtugt3hm0
SceneProfiles:
  - DisplayName:
      zh-cn: 单机版
      en: Single Service
    Template: "templates/msa.yml"
    Spec:
      Service: "templates/cs.spec.yml"
    Parameters:
      Backend:
        Cpu: 1
        Memory: 4096
        Handler: index.handler
