Parameters:
  Region: "cn-hangzhou"
  Name: "key-rate-limit-plugin"
SceneMetadata:
  Name:
    zh-cn: "key-rate-limit 插件"
    en: "Key Rate Limit Plugin"
  Description:
    zh-cn: "key-rate-limit插件实现了基于特定键值实现限流，键值来源可以是 URL 参数、HTTP 请求头"
    en: "The key-rate-limit plugin implements traffic limiting based on specific key values, which can be URL parameters or HTTP request headers"
  Logo: "resources/icons/scence_logo.png"
SceneProfiles:
  - DisplayName:
      zh-cn: 单机版
      en: Single Service
    Template: "templates/msa.yml"
    Documentation:
      zh-cn: "docs/zh-ch/index.md"
    Parameters:
      Backend:
        Cpu: 1
        Memory: 4096
        Handler: index.handler
