name: Registry Publish

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
    secrets:
      ALIBABA_REGISTRY_V3_PUBLISH_TOKEN:
        required: true
      FC_SERVICE_URL:
        required: true
env:
  SEMVER_TYPE: patch

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.project }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Print project input
        run: |
          echo "当前位置：$(pwd)"
          ls -la
      - name: Configure Git
        run: git config --global core.symlinks false
        shell: bash
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git make jq curl wget
      - name: Generate README
        run: |
          npx msa-tool generate -u ${{ secrets.FC_SERVICE_URL }}
        env:
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_EVENT_BEFORE: ${{ github.event.before }}
      - name: List files
        run: |
          ls -la
      - name: generate publish.yaml
        run: |
          npx msa-tool publish
      - name: install s
        run: |
          npm i @serverless-devs/s@3.1.3 -g
      - name: s registry login
        run: |
          s registry login --token ${{ secrets.ALIBABA_REGISTRY_V3_PUBLISH_TOKEN }}
      - name: release prod
        run: |
          s registry publish
